project:
  type: book

book:
  title: "Literature Reviews and AI"
  author: "Enrico Glerean"
  date: today
  sidebar:
    title: "Literature Reviews and AI<br><span class=\"sidebar-author\">Enrico Glerean</span>"
  chapters:
    - index.qmd
    - ch01-chapter-one.qmd
    - ch02-chapter-two.qmd
    - ch03-chapter-three.qmd
    - ch04-chapter-four.qmd
  appendices:
    - appendix-llms-and-agents.qmd
    - appendix-further-readings.qmd

format:
  html:
    theme:
      light: [cosmo, custom-light.scss]
      dark: [darkly, custom-dark.scss]
    toc: true
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    lightbox: true
